### ISSUE TITLE
Differences between Expo.GLView

### ISSUE THREAD

**Issue by bberak** [expo/expo-graphics#2]
Hi there,

I stumbled upon this repo by accident. I was just wondering what the differences between the expo-graphics View and the Expo.GLView were and why one would choose one over the other?

From a quick glance it appears that expo-graphics handles some use cases such as reloading and resizing - however since it hasn't been documented on the offical Expo docs (or has it?) - so I'm not sure which component you would recommend.

Thanks for all the great stuff.

Cheers!

**Comment by EvanBacon** [comment]
Hey, so this wraps a GLView and it's pretty good for three.js projects. The best way to implement the update timer is kinda a pain to remember: https://github.com/expo/expo-graphics/blob/42d1577bd0420294550052cd7145c82f3fc4a2fd/lib/View/index.native.js#L156-L159 and then I noticed beginners were forgetting to call `gl.endFrameEXP()` so this does it automatically. 
The resizing is pretty handy too as it measures the view instead of the window. 
It cleans up the GL when it unmounts. 
On Android backgrounding the app can have weird effects on GL (a native thing), so this surfaces an option to reload the context when the app returns to the foreground.
This also prevents running GL on a simulator (which causes lockdown).
Finally the view will prevent you from running ARKit on devices that do not have A9 chips, or are running Android.
